In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow as tf
tf.keras.backend.clear_session()

In [2]:
from tensorflow.keras import layers
class Linear(layers.Layer):
  def __init__(self, units=32, input_dim=32):
    super(Linear, self).__init__()
    w_init = tf.random_normal_initializer()
    self.w = tf.Variable(initial_value=w_init(shape=(input_dim, units),
                                              dtype='float32'),
                                              trainable=True)
    b_init = tf.zeros_initializer()
    self.b = tf.Variable(initial_value=b_init(shape=(units,),
                                              dtype='float32'),
                                              trainable=True)

  def call(self, inputs):
    return tf.matmul(inputs, self.w) + self.b

x = tf.ones((2, 2))
linear_layer = Linear(4, 2)
y = linear_layer(x)
print(y)

tf.Tensor(
[[ 0.02999987 -0.01697373  0.03409205 -0.01827599]
 [ 0.02999987 -0.01697373  0.03409205 -0.01827599]], shape=(2, 4), dtype=float32)


In [3]:
from __future__ import print_function
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.externals import joblib

df_data = pd.read_csv("point_result.csv")
df_passid = df_data['user_id', 'type']
columns = df_data.columns[2:]
#RobustScaler标准化
robustscaler=preprocessing.RobustScaler()      #
data_scale=robustscaler.fit_transform(df_data.values[:, 2:]) 
df_new = pd.concat([df_passid, pd.DataFrame(data_scale, columns=columns)], axis=1)
df_new.to_csv("point_result.csv_RobustScaler")
joblib.dump(robustscaler, filename='robustscaler')
del df_data, df_passid, df_new

for item in ['eval_point_result', 'oot_point_result']:
    df_data = pd.read_csv(item)
    df_passid = df_data['user_id', 'type']
    columns = df_data.columns[2:]
    #RobustScaler标准化
    robustscaler = joblib.load('robustscaler')      
    data_scale=robustscaler.fit_transform(df_data.values[:, 2:]) 
    df_new = pd.concat([df_passid, pd.DataFrame(data_scale, columns=columns)], axis=1)
    df_new.to_csv(item + "_RobustScaler")
    del df_data, df_passid, df_new
             

/usr/local/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


FileNotFoundError: [Errno 2] File b'point_result.csv' does not exist: b'point_result.csv'

In [4]:
def maxArea(nums):
    if not nums or not nums[0]:
        return 0
    n = len(nums[0])
    height = [0] * (n+1)
    ans = 0
    for row in nums:
        for i in range(n):
            height[i] = height[i]+1 if row[i]=='1' else 0
        stakc = [-1]
        for i in range(n+1):
            while height[i]<height[sack[-1]]:
                h = height[stakc.pop()]
                w = i-1-stack[-1]
                ans = max(ans, h*w)
            stack.append(i)
    return ans

In [5]:
def maximalRectangle(matrix):
    if not matrix or not matrix[0]:
        return 0
    n = len(matrix[0])
    height = [0] * (n + 1)
    ans = 0
    for row in matrix:
        for i in range(n):
            height[i] = height[i] + 1 if row[i] == '1' else 0
        stack = [-1]
        for i in range(n + 1):
            while height[i] < height[stack[-1]]:
                h = height[stack.pop()]
                w = i - 1 - stack[-1]
                ans = max(ans, h * w)
            stack.append(i)
    return ans    

matrix = [
  ["1","0","1","0","0"],
  ["1","0","1","1","1"],
  ["1","1","1","1","1"],
  ["1","0","0","1","0"]
]
print(maximalRectangle(matrix))

6


In [7]:
def merge(nums1, nums2,m,n):
    m, n = m-1, n-1
    while m>=0 and n>=0:
        if nums1[m]>nums2[n]:
            nums1[m+n+1] = nums1[m]
            m -= 1
        else:
            nums1[m+n+1] = nums2[n]
            n -= 1
    if n!=-1:
        nums1[:n+1] = nums2[:n+1]
    return nums1
nums1 = [1,2,3,0,0,0]
m = 3
nums2 = [2,5,6]  
n = 3
print(merge(nums1, nums2,m,n))

[1, 2, 2, 3, 5, 6]


In [8]:
def merge(nums1, mums2, m, n):
    m, n =m-1, n-1
    while m>=0 and n>=0:
        if nums1[m]>nums2[n]:
            nums1[m+n+1] = nums1[m]
            m -= 1
        else:
            nums[m+n+1] = nums2[n]
            n -= 1
    if n!=-1:
        nums1[:n+1] = nums2[:n+1]
    return nums1  

In [16]:
def subset(S):
    res = [[]]
    S.sort()
    for i in range(len(S)):
        if i == 0 or S[i] != S[i - 1]:
            l = len(res)
        for j in range(len(res) - l, len(res)):
            res.append(res[j] + [S[i]])
    return res

nums = [1,2,2]
print(subset(nums))

[[], [1], [2], [1, 2], [2, 2], [1, 2, 2]]


In [18]:
import numpy as np
x_train_a = np.random.random((1000, 5, 3))


In [19]:
x_train_a

array([[[0.23746818, 0.4818518 , 0.89530834],
        [0.68037639, 0.04703433, 0.04897151],
        [0.38252779, 0.33150866, 0.2426059 ],
        [0.19303766, 0.30975303, 0.27642024],
        [0.61156273, 0.13664204, 0.97837431]],

       [[0.92563459, 0.90337167, 0.77431607],
        [0.55897707, 0.30753782, 0.4583325 ],
        [0.97623223, 0.63133451, 0.83393914],
        [0.08516923, 0.52480564, 0.67938804],
        [0.33668251, 0.89269845, 0.83907634]],

       [[0.12108905, 0.19299932, 0.91652412],
        [0.15713801, 0.3809127 , 0.76621133],
        [0.04799308, 0.99510331, 0.68281666],
        [0.96722755, 0.77566851, 0.88294045],
        [0.62428182, 0.64003691, 0.40050576]],

       ...,

       [[0.00716064, 0.14194531, 0.07983955],
        [0.38046568, 0.69979242, 0.81539506],
        [0.49800265, 0.12717695, 0.75326751],
        [0.49134302, 0.98264649, 0.04406969],
        [0.53773785, 0.37436503, 0.90350771]],

       [[0.33542648, 0.35205131, 0.89048957],
        [0.37

In [21]:
def subsetWithDup(S):
    res = [[]]
    S.sort()
    for i in range(len(S)):
        if i==0 or S[i]!=S[i-1]:
            l = len(res)
        for j in range(len(res)-l, len(res)):
            res.append(res[j]+[S[i]])
    return res
S = [1,2,2]
print(subsetWithDup(S))

[[], [1], [2], [1, 2], [2, 2], [1, 2, 2]]


In [22]:
def buildTree(preorder, inorder):
    if inorder:
        ind = inorder.index(preorder.pop(0))
        root = TreeNode(inorder[ind])
        root.left = buildTree(preorder, inorder[0:ind])
        root.right = buildTree(preorder, inorder[ind+1:])
        return root
    

In [23]:
def buildTree(preorder, inorder):
    if inorder:
        ind = inorder.index(preorder.pop(0))
        root = TreeNode(inorder[ind])
        root.left = buildTree(preorder, inorder[0:ind])
        root.right = buildTree(preorder, inorder[ind+1:])
        return root

In [24]:
def buildTree(inorder, postorder):
    if not inorder or not postorder:
        return None
    root = TreeNode(postorder.pop())
    inorderIndex = inorder.index(root.val)
    root.left = buildTree(inorder[inorderIndex+1:],postorder)
    root.right = buildTree(inorder[:inorderIndex], postorder)
    return root

In [25]:
def buildTree(inorder, postorder):
    if not inorder or not postorder:
        return None
    root = TreeNode(postorder.pop())
    inorderIndex = inorder.index(root.val)
    root.right = buildTree(inorder[inorderIndex+1:], postorder)
    root.left = buildTree(inorder[:inorderIndex], postorder)
    return root

In [26]:
def maxProfit(prices):
    max_profit, min_price = 0, float('inf')
    for item in prices:
        min_price = min(min_price, item)
        max_profit = max(max_profit, item-min_price)
    return max_profit

In [27]:
def maxProfit(prices):
    max_profit, min_price = 0, float('inf')
    for item in prices:
        min_price = min(item, min_price)
        max_profit = max(max_profit, item-min_price)
    return max_profit

In [28]:
def maxProfit(prices):
    maxProfit = 0
    for i in range(1, len(prices)):
        if prices[i]>prices[i-1]:
            maxProfit += prices[i] - prices[i-1]
    return maxProfit

In [29]:
def maxProfit(prices):
    maxProfit = 0
    for i in range(1, len(prices)):
        if prices[i]>prices[i-1]:
            maxProfit += prices[i]-prices[i-1]
    return maxProfit

In [31]:
def maxProfit(prices):
    n = len(prices)
    if n==0:
        return 0
    dp = [0 for i in range(n)]
    tmp = 0
    for i in range(1, 3):
        balance = -prices[0]
        tmp = dp[0]
        for j in range(1,n):
            copy = dp[j]
            dp[j] = max(dp[j-1], balance+prices[j])
            balance = max(balance, tmp-prices[j])
            tmp = copy
    return dp[n-1]
prices = [3,3,5,0,0,3,1,4]
print(maxProfit(prices))

6


In [35]:
def longConsecutive(nums):
    long_streak = 0
    num_set = set(nums)
    for item in num_set:
        if item-1 not in num_set:
            current_num = item
            current_streak = 1
            while current_num + 1 in num_set:
                current_num += 1
                current_streak += 1
            long_streak = max(long_streak, current_streak)
    return long_streak
nums = [100, 4, 200, 1, 3, 2]
print(longConsecutive(nums))

4


In [36]:
def longConsecutive(nums):
    long_streak = 0
    num_set = set(nums)
    for item in num_set:
        if item-1 not in num_set:
            current_num = item
            current_streak = 1
            while current_num+1 in num_set:
                current_num += 1
                current_streak += 1
            long_streak = max(long_streak, current_streak)
    return long_streak

In [37]:
def longConsecutive(nums):
    long_streak = 0
    num_set = set(nums)
    for item in num_set:
        if item-1 not in num_set:
            current_num = item
            current_streak = 1
            while current_num+1 in num_set:
                current_num += 1
                current_streak += 1
            long_streak = max(long_streak, current_streak)
    return long_streak

In [39]:
def maxProduct(nums):
    if not nums:
        return
    locMin = locMax = gloMax = nums[0]
    for i in range(1, len(nums)):
        tmp = locMin
        locMin = min(locMax*nums[i], nums[i], locMax*nums[i])
        gloMax = max(gloMax, locMax)
    return gloMax
nums = [2,3,-2,4]
print(maxProduct(nums))

6


In [41]:
def maxProduct(nums):
    if not nums:
        return
    locMin = locMax = gloMax = nums[0]
    for i in range(1, len(nums)):
        tmp = locMin
        locMin = min(locMin*nums[i], nums[i], locMax*nums[i])
        locMax = max(tmp*nums[i], nums[i], locMax*nums[i])
        gloMax = max(gloMax, locMax)
    return glomax